### ISSUE TITLE
Can't run at Openshift

### ISSUE THREAD

**Issue by asxtray** [Praqma/Network-MultiTool#21]
Openshift runs images as non-root. As a result:

The directory /usr/share/nginx/html is not mounted.
Over-writing the default index.html file with some useful information.
/docker-entrypoint.sh: line 25: can't create /usr/share/nginx/html/index.html: Permission denied
nginx: [alert] could not open error log file: open() "/var/lib/nginx/logs/error.log" failed (13: Permission denied)
2021/08/13 13:28:48 [warn] 1#1: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:3
2021/08/13 13:28:48 [emerg] 1#1: cannot load certificate "/certs/server.crt": BIO_new_file() failed (SSL: error:0200100D:system library:fopen:Permission denied:fopen('/certs/server.crt','r') error:2006D002:BIO routines:BIO_new_file:system lib)

**Comment by KamranAzeem** [comment]
Alright, so write permissions on the files - or even reading from files - is not the only issue here. I can introduce a normal user somewhere in the Dockerfile, and then switch to that user, ensure that certain files are readable and writable by that "normal user", BUT, a bigger problem awaits. Nginx will want to use port 80 and 443, and any non-privileged user cannot acquire ports 0- 1023. That means, I would also need to change port to a non-privileged port, say 8080. This will break functionality for almost everyone else using this image. 

Bitnami claims to solve the problem by using a normal user, so it runs as non-root, but if you look closely, their Dockerfile and the related nginx.conf file clearly shows that nginx is configured to listen on 8080, instead of 80.  Reference: https://github.com/bitnami/bitnami-docker-nginx 

To make it "openshift friendly", and to ensure that the functionality does not break for millions of people,  I have to jump through some hoops, or perhaps create a separate branch which does things differently. I need to find time to do that. You have to wait a little.
