### ISSUE TITLE
[feature] Multi arch would be nice

### ISSUE THREAD

**Issue by Turiok** [Praqma/Network-MultiTool#8]
Hello,

I have problems with my DNS resolution on docker compose.
I've seen your image to have the possibility to check my problems.
Sadly. My compose run on raspberry. 
It would be nice to have this image on armhf architecture

**Comment by KamranAzeem** [comment]
Hi. 
Apologies for very late reply. It has almost a year since this issue was created. Corona, and several other things prevented me from working on it. 

Thank you for this feature request, and thanks for waiting for this long. 

It now supports these platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
